# Optional credential, allows easily switching out of SECRET_ACCESS_KEY *and* ACCESS_KEY_ID
# Can be omitted if using another DNS01 validation method or using ambient credentials

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: route53-acme-credentials
  namespace: cert-manager
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCF1IDiv9fUQTQPNuc9+QfsU6L788iZB1Hp1nI+k5SUsvndh5Kq6zvegr50LmnskGmKeapOb4qxsKpCnnJl7o+BfgqF+aVuVQ/GjNIBwhBd8wnFq2BunCVTJBlvMVleMbdcbcinHRP1nKM8nVmnXAagyM4a0EKFc6UIA7afFsaGZLmMcWUDWBV2ksDU2dcvz/5Qg7GY9d/HlPwrhmtYl9LAkmSuFM+Xc5XtjkF33czYBbwkQC27K20ytsKJvSG3Ta8kQT1PB0JA17vOb390RygSleFCOgKDDltQ5oYaCsUGzX9KJXYaV064IOBBvQSvvl1xUNNZzBRsSkBf0Ez6obzz9WLSkhZSsfc8YD+NNqupVBmUI6tocQ0ubkyuS7cVKZmHOOL1AbaOtVU07ZukrxrepPqeys5EFOTJ0aCnOAKJXFGyk7/y7RlPcHusYgjP2vGLjuB7WRmSczjnq8szoUMJOsqbgiY9rJZElvapFRc4EMYqy9Z6KL994eOwn4a0rwU1Wn18pP/Qkhl4Pp9K2G4WI1FEM9gcx9aKLFaMzalvwiYxyriJsGTdjM1sPK3JO9kh190Xrp2dFss9VozoDahpFg9QDZceP/8JUDv4WUOiKua2CNf+rr1HKdpaGtqdpFgoM6tJ3XrFBdprG3y8rEAHClWoBuxuLymMWaGDaWMbdAmG2f8x6uOy5dPVgSW7R6/oZfw8YOwCH39ySIvR1bwTWG1f4Q==
    AWS_SECRET_ACCESS_KEY: AgAxS6P//D5NH2GLdpBdw4w116lcSTyku+PIxWpuB/Gx+xZ1P6uv513lc96MCHEhfgMCiKtbiHBjEHCR8Mf5Z2eWfwmQv5SqvLggQT4UqTqDQgnF6/OstmYh1XQoy+/lKGPYlddiIG8qcw2TZHyIh0lhisecAVUNn1EhiY524Uto3xQfz2RteDSdpzzlDBLa7frIcM2Mo28s6a0SBAkIGWKmQKP5dZujVY/c7SUU75C9/1TPkjR+RNaPQcUqQcQ7Firuh1bJJp+UZaPG4byfZgu+GGLlw9afxcXYBCy8UqJMeUc/bTQ1ZlI9hmW62wFAPKuKW6veTOi7qLkktridPVxewXq8fpmdBKZUp4P/ZS+jymLq9QLSfyEGNCF5go53pKR87ED3FGqRRZ2D1m7/jdsJqjNICGw6kD5rFny+YCK4uVmuXzqDvgwrs7vA/rJXXT/EpJj0dYhYTL8MOTiZeq+SkMfGQKESzRh1KYiD4OxwoEZb5LZL3m6lymzSuMi0tucEr8oJO5Z+zLrLcE8MAnof9A534mOCkLmT9wpxNCF18hPb5/GPfVWCjO5w0D5xDM05D4GXthKaNF2k4O7mqE4PBQKcjpEGf9mxqlj/O3PkXGaRMsGQ8NwfOaeLKHEC1T44594Z2EB/Y9tY3NOrnwQ0aB5gKVNaOmXKeT3ZgswCPWSTrXMAXErnLFHkgG5K4gXuJ7dmjLxK8Iztvu2cpfac4VAfOhCnWCmy/RI/scQ29S/SjQUmoDkx
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: route53-acme-credentials
      namespace: cert-manager
