
image:
  tag: 'v2.8'

deployment:
  # We deploy via GitOps and therefore already have full revision history, no need for maintaining old replicaSets
  revisionHistoryLimit: 1

# Disable anonymous datacollection and other phone-home
globalArguments: []

providers:
  kubernetesIngress:
    publishedService:
      # This doesn't work for non loadbalancer services
      enabled: false

additionalArguments:
  # Set canned status response on ingress status to make argocd happy
  - "--providers.kubernetesingress.ingressendpoint.hostname=nodeport"

ports:
  websecure:
    nodePort: 30443
    tls:
      enabled: true
  web:
    nodePort: 30080
    # Redirect everything on port 80 to 443
    redirectTo: websecure

service:
  type: NodePort
